apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - prometheus
  - grafana
  - kube-state-metrics
  - node-exporter

commonLabels:
  app.kubernetes.io/part-of: monitoring
  app.kubernetes.io/managed-by: kustomize

images:
  - name: prom/prometheus
    newName: prom/prometheus
    newTag: v2.47.0
  - name: grafana/grafana
    newName: grafana/grafana
    newTag: 10.2.0
  - name: k8s.gcr.io/kube-state-metrics/kube-state-metrics
    newName: registry.k8s.io/kube-state-metrics/kube-state-metrics
    newTag: v2.9.2
  - name: prom/node-exporter
    newName: prom/node-exporter
    newTag: v1.6.1
