version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "gamedin"
    assignees:
      - "gamedin"
    commit-message:
      prefix: "npm"
      prefix-development: "npm-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
    ignore:
      # Ignore updates to packages that are known to cause issues
      - dependency-name: "hardhat"
        versions: ["3.x"]
      - dependency-name: "@openzeppelin/contracts"
        versions: ["6.x"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "gamedin"
    assignees:
      - "gamedin"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "gamedin"
    assignees:
      - "gamedin"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  # Enable version updates for Terraform
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "gamedin"
    assignees:
      - "gamedin"
    commit-message:
      prefix: "terraform"
      include: "scope"
    labels:
      - "dependencies"
      - "terraform" 