# These are supported funding model platforms

github: [gamedin] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: gamedin # Replace with a single Patreon username
open_collective: gamedin # Replace with a single Open Collective username
ko_fi: gamedin # Replace with a single Ko-fi username
tidelift: gamedin # Replace with a single Tidelift username
community_bridge: gamedin # Replace with a single Community Bridge project-name
liberapay: gamedin # Replace with a single Liberapay username
issuehunt: gamedin # Replace with a single IssueHunt username
otechie: gamedin # Replace with a single Otechie username
custom: ["https://gamedin.io/donate", "https://opencollective.com/gamedin"] # Replace with up to 4 custom sponsorship URLs 