site_name: Divina L3
site_url: https://Divina-L3.SolarKhan.github.io
docs_dir: docs
nav:
  - Home: index.md
  - Divine Law: COVENANT.md
  - Architecture: ARCHITECTURE.md
  - Developer Guide: DEVELOPER_GUIDE.md
theme:
  name: readthedocs
