apiVersion: v1
kind: Service
metadata:
  name: gamedin-node
  namespace: staging
  labels:
    app: gamedin-node
    env: staging
spec:
  type: ClusterIP
  ports:
  - port: 8545
    targetPort: 8545
    protocol: TCP
    name: rpc
  - port: 8546
    targetPort: 8546
    protocol: TCP
    name: ws
  selector:
    app: gamedin-node
    env: staging
