apiVersion: v1
kind: Service
metadata:
  name: gamedin-dapp
  namespace: staging
  labels:
    app: gamedin-dapp
    env: staging
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: gamedin-dapp
    env: staging
