apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

# Include all necessary resources
resources:
  - namespace.yaml
  - configmaps/gamedin-config.yaml
  - secrets/gamedin-secrets.yaml
  - deployment-dapp.yaml
  - deployment-node.yaml
  - service-dapp.yaml
  - services/gamedin-node.yaml
  - ingress/gamedin-ingress.yaml

# Configure image overrides
images:
  - name: gamedin-dapp
    newName: public.ecr.aws/docker/library/nginx
    newTag: latest
  - name: gamedin-node
    newName: public.ecr.aws/docker/library/nginx
    newTag: latest

# Add common labels to all resources
commonLabels:
  app.kubernetes.io/part-of: gamedin
  app.kubernetes.io/environment: staging
  app.kubernetes.io/managed-by: kustomize

# Configure name prefix and suffix
namePrefix: ""
nameSuffix: ""

# Configure the namespace
namespace: staging

# Add common annotations to all resources
commonAnnotations:
  kustomize.toolkit.fluxcd.io/checksum: ${KUSTOMIZE_CHECKSUM}
  fluxcd.io/automated: "true"
  
# Configure secret and configmap generator if needed
# secretGenerator:
# - name: gamedin-secrets
#   namespace: staging
#   literals:
#     - DB_PASSWORD=${DB_PASSWORD}
#     - API_KEY=${API_KEY}
#   type: Opaque

# configMapGenerator:
# - name: gamedin-config
#   namespace: staging
#   literals:
#     - NODE_ENV=staging
#     - API_URL=${API_URL}
