apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamedin-dapp
  namespace: staging
  labels:
    app: gamedin-dapp
    env: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gamedin-dapp
      env: staging
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gamedin-dapp
        env: staging
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
    spec:
      containers:
      - name: gamedin-dapp
        image: ${ECR_REGISTRY}/gamedin/staging/dapp:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: gamedin-config
        - secretRef:
            name: gamedin-secrets
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
      imagePullSecrets:
      - name: ecr-credentials
