apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamedin-node
  namespace: staging
  labels:
    app: gamedin-node
    env: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gamedin-node
      env: staging
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gamedin-node
        env: staging
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8545"
    spec:
      containers:
      - name: gamedin-node
        image: ${ECR_REGISTRY}/gamedin/staging/node:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 8545
        envFrom:
        - configMapRef:
            name: gamedin-config
        - secretRef:
            name: gamedin-secrets
        livenessProbe:
          httpGet:
            path: /health
            port: 8545
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8545
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 4Gi
      imagePullSecrets:
      - name: ecr-credentials
