apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - deployments/gamedin-dapp.yaml
  - services/gamedin-dapp.yaml
  - deployments/gamedin-node.yaml
  - services/gamedin-node.yaml
  - ingress/gamedin-ingress.yaml

images:
  - name: gamedin-dapp
    newName: ${ECR_REGISTRY}/gamedin/production/dapp
    newTag: ${IMAGE_TAG}
  - name: gamedin-node
    newName: ${ECR_REGISTRY}/gamedin/production/node
    newTag: ${IMAGE_TAG}
