apiVersion: v1
kind: Secret
metadata:
  name: gamedin-secrets
  namespace: staging
type: Opaque
data:
  # These are example values. In production, use proper secret management.
  DB_PASSWORD: ""  # Base64 encoded value
  JWT_SECRET: ""   # Base64 encoded value
  INFURA_API_KEY: ""  # Base64 encoded value
