apiVersion: v1
kind: Secret
metadata:
  name: gamedin-secrets
  namespace: staging
  labels:
    app.kubernetes.io/environment: staging
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: gamedin
type: Opaque
stringData:
  # Database Configuration
  DATABASE_URL: "postgresql://user:${DB_PASSWORD}@db-host:5432/gamedin-staging"
  
  # Authentication
  JWT_SECRET: "${JWT_SECRET}"  # Generate a strong secret in production
  AUTH_SECRET: "${AUTH_SECRET}"  # Generate a strong secret in production
  NEXTAUTH_SECRET: "${NEXTAUTH_SECRET}"  # For NextAuth.js
  
  # External Services
  INFURA_API_KEY: "${INFURA_API_KEY}"  # For blockchain interactions
  ALCHEMY_API_KEY: "${ALCHEMY_API_KEY}"  # Alternative to Infura
  
  # Email Service (e.g., SendGrid, AWS SES)
  EMAIL_SERVER_HOST: "smtp.sendgrid.net"
  EMAIL_SERVER_PORT: "587"
  EMAIL_SERVER_USER: "apikey"
  EMAIL_SERVER_PASSWORD: "${SENDGRID_API_KEY}"
  EMAIL_FROM: "noreply@gamedin.xyz"
  
  # Storage (e.g., AWS S3)
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  AWS_REGION: "us-west-2"
  S3_BUCKET_NAME: "gamedin-staging"
  
  # Analytics and Monitoring
  SENTRY_AUTH_TOKEN: "${SENTRY_AUTH_TOKEN}"  # For source maps upload
  
  # Feature Flags (sensitive ones)
  ENABLE_BETA_FEATURES: "false"
  
  # Rate Limiting
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX: "100"
  
  # Security
  CORS_ORIGIN: "https://staging.gamedin.xyz"
  NODE_OPTIONS: "--max-http-header-size=16384"  # 16KB
  
  # Session Configuration
  SESSION_SECRET: "${SESSION_SECRET}"  # Generate a strong secret in production
  SESSION_COOKIE_NAME: "__Secure-session-token"
  SESSION_COOKIE_SECURE: "true"
  SESSION_COOKIE_HTTPONLY: "true"
  SESSION_COOKIE_SAME_SITE: "lax"
  
  # CSRF Protection
  CSRF_SECRET: "${CSRF_SECRET}"  # Generate a strong secret in production
  
  # OAuth Providers (if applicable)
  GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
  GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
  DISCORD_CLIENT_ID: "${DISCORD_CLIENT_ID}"
  DISCORD_CLIENT_SECRET: "${DISCORD_CLIENT_SECRET}"
  
  # API Keys
  MAPBOX_API_KEY: "${MAPBOX_API_KEY}"  # If using Mapbox for maps
  
  # Web3 Configuration
  WALLET_CONNECT_PROJECT_ID: "${WALLET_CONNECT_PROJECT_ID}"
  
  # Redis (for caching/sessions)
  REDIS_URL: "redis://redis:6379"
  
  # Monitoring
  NEW_RELIC_LICENSE_KEY: "${NEW_RELIC_LICENSE_KEY}"  # If using New Relic
  
  # Error Tracking
  BUGSNAG_API_KEY: "${BUGSNAG_API_KEY}"  # If using Bugsnag
  
  # CDN Configuration
  CDN_BASE_URL: "https://cdn.gamedin.xyz/staging"
  
  # Feature Flags (Remote Config)
  FEATURE_FLAG_API_URL: "https://config.gamedin.xyz/api/v1/flags"
  
  # Performance Monitoring
  ENABLE_APM: "true"
  
  # Logging
  LOG_LEVEL: "debug"
  ENABLE_STRUCTURED_LOGGING: "true"
  
  # Security Headers
  CONTENT_SECURITY_POLICY: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.gamedin.xyz wss://*.gamedin.xyz;"
